name: Run compilation tests

on:
  pull_request:
    branches:
     - master

jobs:
  build:
    name: compilation
    runs-on: ubuntu-24.04
    env:
      CI_CONTAINER: udisks-ci-compilation
    steps:
      - name: Checkout udisks repository
        uses: actions/checkout@v6

      - name: Install podman
        run: |
          sudo apt -qq update
          sudo apt -y -qq install podman

      - name: Build the container
        run: |
          podman build --no-cache -t ${{ env.CI_CONTAINER }} -f misc/ci.Dockerfile .

      - name: Start the container
        run: |
          podman run -d -t --name ${{ env.CI_CONTAINER }} --privileged --volume "$(pwd):/app" --workdir "/app" ${{ env.CI_CONTAINER }}

      - name: Install test dependencies in the container
        run: |
          podman exec -it ${{ env.CI_CONTAINER }} bash -c "ansible-playbook -i "localhost," -c local misc/install-test-dependencies.yml"

      - name: Remove libblockdev SMART plugin
        run: |
          podman exec -it ${{ env.CI_CONTAINER }} bash -c "dnf -y remove libblockdev-smart libblockdev-smartmontools libblockdev-smart-devel"

      - name: Compile UDisks with SMART disabled
        run: |
          podman exec -it ${{ env.CI_CONTAINER }} bash -c "./autogen.sh --disable-smart && make -j"
